# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/
name = "secretdef-web"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./dist/client"
